import fs from 'node:fs/promises'
import path from 'node:path'
import { eq, inArray } from 'drizzle-orm'
import { nanoid } from 'nanoid'
import { loadImage } from '@napi-rs/canvas'
import { config } from './config'
import { getDb, schema } from './db'
import type { Media } from './db/schema'

const EXT: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
}

export const ALLOWED_UPLOAD_TYPES = Object.keys(EXT)
export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024

function mediaDir() {
  return path.join(config.dataDir, 'media')
}

function filePath(row: Pick<Media, 'filename'>) {
  // filename is always generated by us (id + ext), never user supplied.
  return path.join(mediaDir(), path.basename(row.filename))
}

export async function saveMedia(
  buf: Buffer,
  mime: string,
  opts: { kind: Media['kind']; label?: string; width?: number; height?: number },
): Promise<Media> {
  const ext = EXT[mime]
  if (!ext) throw new Error(`Unsupported image type: ${mime}`)
  let { width, height } = opts
  if (width == null || height == null) {
    // Decoding also validates that the bytes are really an image.
    const img = await loadImage(buf)
    width = img.width
    height = img.height
  }
  const id = nanoid(12)
  const row: Media = {
    id,
    filename: `${id}.${ext}`,
    mime,
    width,
    height,
    bytes: buf.length,
    kind: opts.kind,
    label: opts.label ?? null,
    createdAt: Date.now(),
  }
  await fs.mkdir(mediaDir(), { recursive: true })
  await fs.writeFile(filePath(row), buf)
  const db = await getDb()
  await db.insert(schema.media).values(row)
  return row
}

export async function getMedia(id: string): Promise<Media | undefined> {
  const db = await getDb()
  return db.query.media.findFirst({ where: eq(schema.media.id, id) })
}

export async function getMediaMany(ids: string[]): Promise<Media[]> {
  if (ids.length === 0) return []
  const db = await getDb()
  const rows = await db.select().from(schema.media).where(inArray(schema.media.id, ids))
  // Preserve the requested order.
  return ids.map((id) => rows.find((r) => r.id === id)).filter((r): r is Media => !!r)
}

export async function readMediaFile(row: Media): Promise<Buffer> {
  return fs.readFile(filePath(row))
}

export async function deleteMedia(id: string) {
  const row = await getMedia(id)
  if (!row) return
  await fs.rm(filePath(row), { force: true })
  const db = await getDb()
  await db.delete(schema.media).where(eq(schema.media.id, id))
}
