/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppComposeRouteImport } from './routes/_app/compose'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppPostsRouteImport } from './routes/_app/posts'
import { Route as AppRashifalRouteImport } from './routes/_app/rashifal'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWeatherRouteImport } from './routes/_app/weather'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates.index'
import { Route as AppTemplatesIdRouteImport } from './routes/_app/templates.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRoute = AppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppRashifalRoute = AppRashifalRouteImport.update({
  id: '/rashifal',
  path: '/rashifal',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWeatherRoute = AppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AppRoute,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIdRoute = AppTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/automations': typeof AppAutomationsRoute
  '/compose': typeof AppComposeRoute
  '/library': typeof AppLibraryRoute
  '/media': typeof AppMediaRoute
  '/posts': typeof AppPostsRoute
  '/rashifal': typeof AppRashifalRoute
  '/settings': typeof AppSettingsRoute
  '/weather': typeof AppWeatherRoute
  '/api/cron': typeof ApiCronRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/automations': typeof AppAutomationsRoute
  '/compose': typeof AppComposeRoute
  '/library': typeof AppLibraryRoute
  '/media': typeof AppMediaRoute
  '/posts': typeof AppPostsRoute
  '/rashifal': typeof AppRashifalRoute
  '/settings': typeof AppSettingsRoute
  '/weather': typeof AppWeatherRoute
  '/api/cron': typeof ApiCronRoute
  '/': typeof AppIndexRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/templates': typeof AppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/compose': typeof AppComposeRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/posts': typeof AppPostsRoute
  '/_app/rashifal': typeof AppRashifalRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/weather': typeof AppWeatherRoute
  '/api/cron': typeof ApiCronRoute
  '/_app/': typeof AppIndexRoute
  '/_app/templates/$id': typeof AppTemplatesIdRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/automations'
    | '/compose'
    | '/library'
    | '/media'
    | '/posts'
    | '/rashifal'
    | '/settings'
    | '/weather'
    | '/api/cron'
    | '/templates/$id'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/automations'
    | '/compose'
    | '/library'
    | '/media'
    | '/posts'
    | '/rashifal'
    | '/settings'
    | '/weather'
    | '/api/cron'
    | '/'
    | '/templates/$id'
    | '/templates'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/automations'
    | '/_app/compose'
    | '/_app/library'
    | '/_app/media'
    | '/_app/posts'
    | '/_app/rashifal'
    | '/_app/settings'
    | '/_app/weather'
    | '/api/cron'
    | '/_app/'
    | '/_app/templates/$id'
    | '/_app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCronRoute: typeof ApiCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compose': {
      id: '/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rashifal': {
      id: '/_app/rashifal'
      path: '/rashifal'
      fullPath: '/rashifal'
      preLoaderRoute: typeof AppRashifalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weather': {
      id: '/_app/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AppWeatherRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$id': {
      id: '/_app/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AppTemplatesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppComposeRoute: typeof AppComposeRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMediaRoute: typeof AppMediaRoute
  AppPostsRoute: typeof AppPostsRoute
  AppRashifalRoute: typeof AppRashifalRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeatherRoute: typeof AppWeatherRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTemplatesIdRoute: typeof AppTemplatesIdRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppComposeRoute: AppComposeRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMediaRoute: AppMediaRoute,
  AppPostsRoute: AppPostsRoute,
  AppRashifalRoute: AppRashifalRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeatherRoute: AppWeatherRoute,
  AppIndexRoute: AppIndexRoute,
  AppTemplatesIdRoute: AppTemplatesIdRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCronRoute: ApiCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
